/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import type {
  RemoteResult,
  TypertRemoteContribution,
} from '@deepseek-ai/dsh-typert-protocol'
import type { TavernAckValue, TavernCancelDraftRequest, TavernCommitImportRequest, TavernCommitImportValue, TavernCreateSessionRequest, TavernCreateSessionValue, TavernDeleteCardRequest, TavernEditDirtyRequest, TavernEditDirtyValue, TavernEnsureWriterRequest, TavernEnsureWriterValue, TavernFileOpRequest, TavernImportLibraryRequest, TavernLibraryValue, TavernLoadRequest, TavernOpeningValue, TavernPromptRequest, TavernPromptValue, TavernPublishRequest, TavernPublishValue, TavernReadAssetRequest, TavernReadAssetValue, TavernReadLibraryAssetRequest, TavernReadLibraryAssetValue, TavernReadTextRequest, TavernReadTextValue, TavernRebindValue, TavernRetryPointValue, TavernRunScriptRequest, TavernRunScriptValue, TavernSaveEditRequest, TavernSaveRequest, TavernSavesValue, TavernSessionRequest, TavernStateValue, TavernStopRequest, TavernStopValue, TavernTailTranscriptValue, TavernTreeValue, TavernWorkspacesValue, TavernWriteAssetRequest, TavernWriteTextRequest } from 'dsh-tavern-fengyue-api/types'

declare module '@deepseek-ai/dsh-typert-protocol' {
  interface TypertRemoteNamespace$74617665726e {
    cancelDraft: (request: TavernCancelDraftRequest, signal?: AbortSignal) => Promise<RemoteResult<TavernAckValue>>
    cancelEdit: (request: TavernSessionRequest, signal?: AbortSignal) => Promise<RemoteResult<TavernAckValue>>
    commitImport: (request: TavernCommitImportRequest, signal?: AbortSignal) => Promise<RemoteResult<TavernCommitImportValue>>
    createSession: (_request: TavernCreateSessionRequest, signal?: AbortSignal) => Promise<RemoteResult<TavernCreateSessionValue>>
    deleteCard: (request: TavernDeleteCardRequest, signal?: AbortSignal) => Promise<RemoteResult<TavernAckValue>>
    deleteSave: (request: TavernLoadRequest, signal?: AbortSignal) => Promise<RemoteResult<TavernAckValue>>
    deleteSession: (request: TavernSessionRequest, signal?: AbortSignal) => Promise<RemoteResult<TavernAckValue>>
    draftCard: (request: TavernSessionRequest, signal?: AbortSignal) => Promise<RemoteResult<TavernAckValue>>
    editDirty: (request: TavernEditDirtyRequest, signal?: AbortSignal) => Promise<RemoteResult<TavernEditDirtyValue>>
    editFromLibrary: (request: TavernImportLibraryRequest, signal?: AbortSignal) => Promise<RemoteResult<TavernAckValue>>
    ensureWriter: (request: TavernEnsureWriterRequest, signal?: AbortSignal) => Promise<RemoteResult<TavernEnsureWriterValue>>
    fileOp: (request: TavernFileOpRequest, signal?: AbortSignal) => Promise<RemoteResult<TavernAckValue>>
    importFromLibrary: (request: TavernImportLibraryRequest, signal?: AbortSignal) => Promise<RemoteResult<TavernAckValue>>
    library: (_request: Record<never, never>, signal?: AbortSignal) => Promise<RemoteResult<TavernLibraryValue>>
    load: (request: TavernLoadRequest, signal?: AbortSignal) => Promise<RemoteResult<TavernRebindValue>>
    opening: (request: TavernSessionRequest, signal?: AbortSignal) => Promise<RemoteResult<TavernOpeningValue>>
    prompt: (request: TavernPromptRequest, signal?: AbortSignal) => Promise<RemoteResult<TavernPromptValue>>
    publishCard: (request: TavernPublishRequest, signal?: AbortSignal) => Promise<RemoteResult<TavernPublishValue>>
    readAsset: (request: TavernReadAssetRequest, signal?: AbortSignal) => Promise<RemoteResult<TavernReadAssetValue>>
    readLibraryAsset: (request: TavernReadLibraryAssetRequest, signal?: AbortSignal) => Promise<RemoteResult<TavernReadLibraryAssetValue>>
    readText: (request: TavernReadTextRequest, signal?: AbortSignal) => Promise<RemoteResult<TavernReadTextValue>>
    reset: (request: TavernSessionRequest, signal?: AbortSignal) => Promise<RemoteResult<TavernRebindValue>>
    retryPoint: (request: TavernSessionRequest, signal?: AbortSignal) => Promise<RemoteResult<TavernRetryPointValue>>
    runScript: (request: TavernRunScriptRequest, signal?: AbortSignal) => Promise<RemoteResult<TavernRunScriptValue>>
    save: (request: TavernSaveRequest, signal?: AbortSignal) => Promise<RemoteResult<TavernAckValue>>
    saveEdit: (request: TavernSaveEditRequest, signal?: AbortSignal) => Promise<RemoteResult<TavernPublishValue>>
    saves: (request: TavernSessionRequest, signal?: AbortSignal) => Promise<RemoteResult<TavernSavesValue>>
    state: (request: TavernSessionRequest, signal?: AbortSignal) => Promise<RemoteResult<TavernStateValue>>
    stop: (request: TavernStopRequest, signal?: AbortSignal) => Promise<RemoteResult<TavernStopValue>>
    tailTranscript: (request: TavernSessionRequest, signal?: AbortSignal) => Promise<RemoteResult<TavernTailTranscriptValue>>
    tree: (request: TavernSessionRequest, signal?: AbortSignal) => Promise<RemoteResult<TavernTreeValue>>
    workspaces: (_request: Record<never, never>, signal?: AbortSignal) => Promise<RemoteResult<TavernWorkspacesValue>>
    writeAsset: (request: TavernWriteAssetRequest, signal?: AbortSignal) => Promise<RemoteResult<TavernAckValue>>
    writeText: (request: TavernWriteTextRequest, signal?: AbortSignal) => Promise<RemoteResult<TavernAckValue>>
  }
  interface TypertRemoteMap {
    'tavern/cancelDraft': (request: TavernCancelDraftRequest, signal?: AbortSignal) => Promise<RemoteResult<TavernAckValue>>
    'tavern/cancelEdit': (request: TavernSessionRequest, signal?: AbortSignal) => Promise<RemoteResult<TavernAckValue>>
    'tavern/commitImport': (request: TavernCommitImportRequest, signal?: AbortSignal) => Promise<RemoteResult<TavernCommitImportValue>>
    'tavern/createSession': (_request: TavernCreateSessionRequest, signal?: AbortSignal) => Promise<RemoteResult<TavernCreateSessionValue>>
    'tavern/deleteCard': (request: TavernDeleteCardRequest, signal?: AbortSignal) => Promise<RemoteResult<TavernAckValue>>
    'tavern/deleteSave': (request: TavernLoadRequest, signal?: AbortSignal) => Promise<RemoteResult<TavernAckValue>>
    'tavern/deleteSession': (request: TavernSessionRequest, signal?: AbortSignal) => Promise<RemoteResult<TavernAckValue>>
    'tavern/draftCard': (request: TavernSessionRequest, signal?: AbortSignal) => Promise<RemoteResult<TavernAckValue>>
    'tavern/editDirty': (request: TavernEditDirtyRequest, signal?: AbortSignal) => Promise<RemoteResult<TavernEditDirtyValue>>
    'tavern/editFromLibrary': (request: TavernImportLibraryRequest, signal?: AbortSignal) => Promise<RemoteResult<TavernAckValue>>
    'tavern/ensureWriter': (request: TavernEnsureWriterRequest, signal?: AbortSignal) => Promise<RemoteResult<TavernEnsureWriterValue>>
    'tavern/fileOp': (request: TavernFileOpRequest, signal?: AbortSignal) => Promise<RemoteResult<TavernAckValue>>
    'tavern/importFromLibrary': (request: TavernImportLibraryRequest, signal?: AbortSignal) => Promise<RemoteResult<TavernAckValue>>
    'tavern/library': (_request: Record<never, never>, signal?: AbortSignal) => Promise<RemoteResult<TavernLibraryValue>>
    'tavern/load': (request: TavernLoadRequest, signal?: AbortSignal) => Promise<RemoteResult<TavernRebindValue>>
    'tavern/opening': (request: TavernSessionRequest, signal?: AbortSignal) => Promise<RemoteResult<TavernOpeningValue>>
    'tavern/prompt': (request: TavernPromptRequest, signal?: AbortSignal) => Promise<RemoteResult<TavernPromptValue>>
    'tavern/publishCard': (request: TavernPublishRequest, signal?: AbortSignal) => Promise<RemoteResult<TavernPublishValue>>
    'tavern/readAsset': (request: TavernReadAssetRequest, signal?: AbortSignal) => Promise<RemoteResult<TavernReadAssetValue>>
    'tavern/readLibraryAsset': (request: TavernReadLibraryAssetRequest, signal?: AbortSignal) => Promise<RemoteResult<TavernReadLibraryAssetValue>>
    'tavern/readText': (request: TavernReadTextRequest, signal?: AbortSignal) => Promise<RemoteResult<TavernReadTextValue>>
    'tavern/reset': (request: TavernSessionRequest, signal?: AbortSignal) => Promise<RemoteResult<TavernRebindValue>>
    'tavern/retryPoint': (request: TavernSessionRequest, signal?: AbortSignal) => Promise<RemoteResult<TavernRetryPointValue>>
    'tavern/runScript': (request: TavernRunScriptRequest, signal?: AbortSignal) => Promise<RemoteResult<TavernRunScriptValue>>
    'tavern/save': (request: TavernSaveRequest, signal?: AbortSignal) => Promise<RemoteResult<TavernAckValue>>
    'tavern/saveEdit': (request: TavernSaveEditRequest, signal?: AbortSignal) => Promise<RemoteResult<TavernPublishValue>>
    'tavern/saves': (request: TavernSessionRequest, signal?: AbortSignal) => Promise<RemoteResult<TavernSavesValue>>
    'tavern/state': (request: TavernSessionRequest, signal?: AbortSignal) => Promise<RemoteResult<TavernStateValue>>
    'tavern/stop': (request: TavernStopRequest, signal?: AbortSignal) => Promise<RemoteResult<TavernStopValue>>
    'tavern/tailTranscript': (request: TavernSessionRequest, signal?: AbortSignal) => Promise<RemoteResult<TavernTailTranscriptValue>>
    'tavern/tree': (request: TavernSessionRequest, signal?: AbortSignal) => Promise<RemoteResult<TavernTreeValue>>
    'tavern/workspaces': (_request: Record<never, never>, signal?: AbortSignal) => Promise<RemoteResult<TavernWorkspacesValue>>
    'tavern/writeAsset': (request: TavernWriteAssetRequest, signal?: AbortSignal) => Promise<RemoteResult<TavernAckValue>>
    'tavern/writeText': (request: TavernWriteTextRequest, signal?: AbortSignal) => Promise<RemoteResult<TavernAckValue>>
  }
  interface TypertRemoteNamespaceMap {
    'tavern': TypertRemoteNamespace$74617665726e
  }
}

export declare const TYPERT_REMOTE: TypertRemoteContribution
export default TYPERT_REMOTE
//# sourceMappingURL=typert.remote-client.d.ts.map
