/* Generated by @deepseek-ai/dsh-typert-generator from FaceModel — do not edit. */
import { z } from 'zod'

const _deepseek_ai_dsh_api_tavern_tavern_cancelDraft_parameter_0$schema = z.object({
  'sessionId': z.intersection(z.string(), z.unknown()).readonly(),
})
const _deepseek_ai_dsh_api_tavern_tavern_cancelDraft_result$schema = z.object({
  'ok': z.literal(true).readonly(),
})
const _deepseek_ai_dsh_api_tavern_tavern_cancelEdit_parameter_0$schema = z.object({
  'sessionId': z.intersection(z.string(), z.unknown()).readonly(),
})
const _deepseek_ai_dsh_api_tavern_tavern_cancelEdit_result$schema = z.object({
  'ok': z.literal(true).readonly(),
})
const _deepseek_ai_dsh_api_tavern_tavern_commitImport_parameter_0$schema = z.object({
  'sessionId': z.intersection(z.string(), z.unknown()).readonly(),
  'title': z.string().readonly(),
  'files': z.array(z.object({
  'path': z.string().readonly(),
  'content': z.string().readonly(),
})).readonly(),
})
const _deepseek_ai_dsh_api_tavern_tavern_commitImport_result$schema = z.object({
  'name': z.string().readonly(),
})
const _deepseek_ai_dsh_api_tavern_tavern_createSession_parameter_0$schema = z.object({
  'nop': z.undefined().readonly().optional(),
})
const _deepseek_ai_dsh_api_tavern_tavern_createSession_result$schema = z.object({
  'sessionId': z.intersection(z.string(), z.unknown()).readonly(),
})
const _deepseek_ai_dsh_api_tavern_tavern_deleteCard_parameter_0$schema = z.object({
  'name': z.string().readonly(),
})
const _deepseek_ai_dsh_api_tavern_tavern_deleteCard_result$schema = z.object({
  'ok': z.literal(true).readonly(),
})
const _deepseek_ai_dsh_api_tavern_tavern_deleteSave_parameter_0$schema = z.object({
  'sessionId': z.intersection(z.string(), z.unknown()).readonly(),
  'name': z.string().readonly(),
})
const _deepseek_ai_dsh_api_tavern_tavern_deleteSave_result$schema = z.object({
  'ok': z.literal(true).readonly(),
})
const _deepseek_ai_dsh_api_tavern_tavern_deleteSession_parameter_0$schema = z.object({
  'sessionId': z.intersection(z.string(), z.unknown()).readonly(),
})
const _deepseek_ai_dsh_api_tavern_tavern_deleteSession_result$schema = z.object({
  'ok': z.literal(true).readonly(),
})
const _deepseek_ai_dsh_api_tavern_tavern_draftCard_parameter_0$schema = z.object({
  'sessionId': z.intersection(z.string(), z.unknown()).readonly(),
})
const _deepseek_ai_dsh_api_tavern_tavern_draftCard_result$schema = z.object({
  'ok': z.literal(true).readonly(),
})
const _deepseek_ai_dsh_api_tavern_tavern_editDirty_parameter_0$schema = z.object({
  'sessionId': z.intersection(z.string(), z.unknown()).readonly(),
})
const _deepseek_ai_dsh_api_tavern_tavern_editDirty_result$schema = z.object({
  'dirty': z.boolean().readonly(),
})
const _deepseek_ai_dsh_api_tavern_tavern_editFromLibrary_parameter_0$schema = z.object({
  'sessionId': z.intersection(z.string(), z.unknown()).readonly(),
  'name': z.string().readonly(),
})
const _deepseek_ai_dsh_api_tavern_tavern_editFromLibrary_result$schema = z.object({
  'ok': z.literal(true).readonly(),
})
const _deepseek_ai_dsh_api_tavern_tavern_ensureWriter_parameter_0$schema = z.object({
  'sessionId': z.intersection(z.string(), z.unknown()).readonly(),
})
const _deepseek_ai_dsh_api_tavern_tavern_ensureWriter_result$schema = z.object({
  'sessionId': z.intersection(z.string(), z.unknown()).readonly(),
})
const _deepseek_ai_dsh_api_tavern_tavern_fileOp_parameter_0$schema = z.object({
  'sessionId': z.intersection(z.string(), z.unknown()).readonly(),
  'op': z.union([z.object({
  'kind': z.literal("create").readonly(),
  'path': z.string().readonly(),
}), z.object({
  'kind': z.literal("mkdir").readonly(),
  'path': z.string().readonly(),
}), z.object({
  'kind': z.literal("move").readonly(),
  'from': z.string().readonly(),
  'to': z.string().readonly(),
}), z.object({
  'kind': z.literal("delete").readonly(),
  'path': z.string().readonly(),
})]).readonly(),
})
const _deepseek_ai_dsh_api_tavern_tavern_fileOp_result$schema = z.object({
  'ok': z.literal(true).readonly(),
})
const _deepseek_ai_dsh_api_tavern_tavern_importFromLibrary_parameter_0$schema = z.object({
  'sessionId': z.intersection(z.string(), z.unknown()).readonly(),
  'name': z.string().readonly(),
})
const _deepseek_ai_dsh_api_tavern_tavern_importFromLibrary_result$schema = z.object({
  'ok': z.literal(true).readonly(),
})
const _deepseek_ai_dsh_api_tavern_tavern_library_parameter_0$schema = z.object({})
const _deepseek_ai_dsh_api_tavern_tavern_library_result$schema = z.object({
  'cards': z.array(z.object({
  'name': z.string().readonly(),
  'title': z.string().readonly(),
  'desc': z.string().readonly(),
  'cover': z.string().readonly(),
})).readonly(),
})
const _deepseek_ai_dsh_api_tavern_tavern_load_parameter_0$schema = z.object({
  'sessionId': z.intersection(z.string(), z.unknown()).readonly(),
  'name': z.string().readonly(),
})
const _deepseek_ai_dsh_api_tavern_tavern_load_result$schema = z.object({
  'sessionId': z.intersection(z.string(), z.unknown()).readonly(),
  'draft': z.string().readonly(),
})
const _deepseek_ai_dsh_api_tavern_tavern_opening_parameter_0$schema = z.object({
  'sessionId': z.intersection(z.string(), z.unknown()).readonly(),
})
const _deepseek_ai_dsh_api_tavern_tavern_opening_result$schema = z.object({
  'html': z.union([z.literal(null), z.string()]).readonly(),
})
const _deepseek_ai_dsh_api_tavern_tavern_prompt_parameter_0$schema = z.object({
  'sessionId': z.intersection(z.string(), z.unknown()).readonly(),
  'text': z.string().readonly(),
  'requestId': z.string().readonly(),
  'clientTimeZone': z.string().readonly().optional(),
})
const _deepseek_ai_dsh_api_tavern_tavern_prompt_result$schema = z.object({
  'accepted': z.boolean().readonly(),
  'scriptFailures': z.array(z.object({
  'name': z.string().readonly(),
  'reason': z.union([z.literal("parse"), z.literal("depth"), z.literal("args"), z.literal("limit"), z.literal("missing"), z.literal("exit"), z.literal("timeout"), z.literal("abort")]).readonly(),
  'exitCode': z.number().readonly().optional(),
})).readonly().optional(),
})
const _deepseek_ai_dsh_api_tavern_tavern_publishCard_parameter_0$schema = z.object({
  'sessionId': z.intersection(z.string(), z.unknown()).readonly(),
})
const _deepseek_ai_dsh_api_tavern_tavern_publishCard_result$schema = z.object({
  'name': z.string().readonly(),
})
const _deepseek_ai_dsh_api_tavern_tavern_readAsset_parameter_0$schema = z.object({
  'sessionId': z.intersection(z.string(), z.unknown()).readonly(),
  'path': z.string().readonly(),
})
const _deepseek_ai_dsh_api_tavern_tavern_readAsset_result$schema = z.object({
  'dataUrl': z.string().readonly(),
})
const _deepseek_ai_dsh_api_tavern_tavern_readLibraryAsset_parameter_0$schema = z.object({
  'name': z.string().readonly(),
  'path': z.string().readonly(),
})
const _deepseek_ai_dsh_api_tavern_tavern_readLibraryAsset_result$schema = z.object({
  'dataUrl': z.string().readonly(),
})
const _deepseek_ai_dsh_api_tavern_tavern_readText_parameter_0$schema = z.object({
  'sessionId': z.intersection(z.string(), z.unknown()).readonly(),
  'path': z.string().readonly(),
})
const _deepseek_ai_dsh_api_tavern_tavern_readText_result$schema = z.object({
  'text': z.string().readonly(),
})
const _deepseek_ai_dsh_api_tavern_tavern_reset_parameter_0$schema = z.object({
  'sessionId': z.intersection(z.string(), z.unknown()).readonly(),
})
const _deepseek_ai_dsh_api_tavern_tavern_reset_result$schema = z.object({
  'sessionId': z.intersection(z.string(), z.unknown()).readonly(),
  'draft': z.string().readonly(),
})
const _deepseek_ai_dsh_api_tavern_tavern_retryPoint_parameter_0$schema = z.object({
  'sessionId': z.intersection(z.string(), z.unknown()).readonly(),
})
const _deepseek_ai_dsh_api_tavern_tavern_retryPoint_result$schema = z.object({
  'sessionId': z.intersection(z.string(), z.unknown()).readonly(),
  'text': z.string().readonly(),
})
const _deepseek_ai_dsh_api_tavern_tavern_runScript_parameter_0$schema = z.object({
  'name': z.string().readonly(),
  'args': z.array(z.string()).readonly(),
  'sessionId': z.intersection(z.string(), z.unknown()).readonly(),
})
const _deepseek_ai_dsh_api_tavern_tavern_runScript_result$schema = z.object({
  'text': z.string().readonly(),
})
const _deepseek_ai_dsh_api_tavern_tavern_save_parameter_0$schema = z.object({
  'sessionId': z.intersection(z.string(), z.unknown()).readonly(),
  'name': z.string().readonly(),
  'draft': z.string().readonly(),
})
const _deepseek_ai_dsh_api_tavern_tavern_save_result$schema = z.object({
  'ok': z.literal(true).readonly(),
})
const _deepseek_ai_dsh_api_tavern_tavern_saveEdit_parameter_0$schema = z.object({
  'sessionId': z.intersection(z.string(), z.unknown()).readonly(),
})
const _deepseek_ai_dsh_api_tavern_tavern_saveEdit_result$schema = z.object({
  'name': z.string().readonly(),
})
const _deepseek_ai_dsh_api_tavern_tavern_saves_parameter_0$schema = z.object({
  'sessionId': z.intersection(z.string(), z.unknown()).readonly(),
})
const _deepseek_ai_dsh_api_tavern_tavern_saves_result$schema = z.object({
  'saves': z.array(z.object({
  'name': z.string().readonly(),
  'type': z.union([z.literal("auto"), z.literal("manual")]).readonly(),
  'summary': z.string().readonly(),
})).readonly(),
})
const _deepseek_ai_dsh_api_tavern_tavern_state_parameter_0$schema = z.object({
  'sessionId': z.intersection(z.string(), z.unknown()).readonly(),
})
const _deepseek_ai_dsh_api_tavern_tavern_state_result$schema = z.object({
  'hasCard': z.boolean().readonly(),
  'maintenanceOn': z.boolean().readonly(),
  'title': z.string().readonly(),
  'desc': z.string().readonly(),
  'cover': z.string().readonly(),
  'drafting': z.boolean().readonly(),
  'editing': z.union([z.literal(null), z.string()]).readonly(),
  'tailRunning': z.boolean().readonly(),
  'retryable': z.boolean().readonly(),
})
const _deepseek_ai_dsh_api_tavern_tavern_stop_parameter_0$schema = z.object({
  'sessionId': z.intersection(z.string(), z.unknown()).readonly(),
})
const _deepseek_ai_dsh_api_tavern_tavern_stop_result$schema = z.object({
  'accepted': z.literal(true).readonly(),
  'tailStopped': z.boolean().readonly(),
})
const _deepseek_ai_dsh_api_tavern_tavern_tailTranscript_parameter_0$schema = z.object({
  'sessionId': z.intersection(z.string(), z.unknown()).readonly(),
})
const _deepseek_ai_dsh_api_tavern_tavern_tailTranscript_result$schema = z.object({
  'tails': z.array(z.object({
  'childId': z.string().readonly(),
  'at': z.number().readonly(),
  'status': z.union([z.literal("completed"), z.literal("stopped"), z.literal("error"), z.literal("archived")]).readonly(),
  'actions': z.array(z.object({
  'tool': z.string().readonly(),
  'detail': z.string().readonly(),
})).readonly(),
  'reply': z.string().readonly(),
})).readonly(),
})
const _deepseek_ai_dsh_api_tavern_tavern_tree_parameter_0$schema = z.object({
  'sessionId': z.intersection(z.string(), z.unknown()).readonly(),
})
const _deepseek_ai_dsh_api_tavern_tavern_tree_result$schema = z.object({
  'entries': z.array(z.object({
  'path': z.string().readonly(),
  'dir': z.boolean().readonly(),
})).readonly(),
})
const _deepseek_ai_dsh_api_tavern_tavern_workspaces_parameter_0$schema = z.object({})
const _deepseek_ai_dsh_api_tavern_tavern_workspaces_result$schema = z.object({
  'rows': z.array(z.object({
  'name': z.string().readonly(),
  'sessionId': z.union([z.literal(null), z.string()]).readonly(),
  'hasCard': z.boolean().readonly(),
  'title': z.string().readonly(),
  'desc': z.string().readonly(),
})).readonly(),
})
const _deepseek_ai_dsh_api_tavern_tavern_writeAsset_parameter_0$schema = z.object({
  'sessionId': z.intersection(z.string(), z.unknown()).readonly(),
  'path': z.string().readonly(),
  'dataBase64': z.string().readonly(),
})
const _deepseek_ai_dsh_api_tavern_tavern_writeAsset_result$schema = z.object({
  'ok': z.literal(true).readonly(),
})
const _deepseek_ai_dsh_api_tavern_tavern_writeText_parameter_0$schema = z.object({
  'sessionId': z.intersection(z.string(), z.unknown()).readonly(),
  'path': z.string().readonly(),
  'text': z.string().readonly(),
})
const _deepseek_ai_dsh_api_tavern_tavern_writeText_result$schema = z.object({
  'ok': z.literal(true).readonly(),
})

export const TYPERT = {
  package: 'dsh-tavern-fengyue-api',
  face: 'host',
  schemas: [
  ],
  invocations: [
    {
      id: 'dsh-tavern-fengyue-api#tavern/cancelDraft',
      service: 'tavernApi',
      namespace: 'tavern',
      method: 'cancelDraft',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-tavern-fengyue-api/types#TavernCancelDraftRequest',
            schema: _deepseek_ai_dsh_api_tavern_tavern_cancelDraft_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-tavern-fengyue-api/types#TavernAckValue',
        schema: _deepseek_ai_dsh_api_tavern_tavern_cancelDraft_result$schema,
      },
      sourceLocation: {"file":"packages/api/tavern/src/index.ts","line":417,"column":9},
    },
    {
      id: 'dsh-tavern-fengyue-api#tavern/cancelEdit',
      service: 'tavernApi',
      namespace: 'tavern',
      method: 'cancelEdit',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-tavern-fengyue-api/types#TavernSessionRequest',
            schema: _deepseek_ai_dsh_api_tavern_tavern_cancelEdit_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-tavern-fengyue-api/types#TavernAckValue',
        schema: _deepseek_ai_dsh_api_tavern_tavern_cancelEdit_result$schema,
      },
      sourceLocation: {"file":"packages/api/tavern/src/index.ts","line":264,"column":9},
    },
    {
      id: 'dsh-tavern-fengyue-api#tavern/commitImport',
      service: 'tavernApi',
      namespace: 'tavern',
      method: 'commitImport',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-tavern-fengyue-api/types#TavernCommitImportRequest',
            schema: _deepseek_ai_dsh_api_tavern_tavern_commitImport_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-tavern-fengyue-api/types#TavernCommitImportValue',
        schema: _deepseek_ai_dsh_api_tavern_tavern_commitImport_result$schema,
      },
      sourceLocation: {"file":"packages/api/tavern/src/index.ts","line":395,"column":9},
    },
    {
      id: 'dsh-tavern-fengyue-api#tavern/createSession',
      service: 'tavernApi',
      namespace: 'tavern',
      method: 'createSession',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: '_request',
          wire: '_request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-tavern-fengyue-api/types#TavernCreateSessionRequest',
            schema: _deepseek_ai_dsh_api_tavern_tavern_createSession_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-tavern-fengyue-api/types#TavernCreateSessionValue',
        schema: _deepseek_ai_dsh_api_tavern_tavern_createSession_result$schema,
      },
      sourceLocation: {"file":"packages/api/tavern/src/index.ts","line":189,"column":9},
    },
    {
      id: 'dsh-tavern-fengyue-api#tavern/deleteCard',
      service: 'tavernApi',
      namespace: 'tavern',
      method: 'deleteCard',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-tavern-fengyue-api/types#TavernDeleteCardRequest',
            schema: _deepseek_ai_dsh_api_tavern_tavern_deleteCard_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-tavern-fengyue-api/types#TavernAckValue',
        schema: _deepseek_ai_dsh_api_tavern_tavern_deleteCard_result$schema,
      },
      sourceLocation: {"file":"packages/api/tavern/src/index.ts","line":234,"column":9},
    },
    {
      id: 'dsh-tavern-fengyue-api#tavern/deleteSave',
      service: 'tavernApi',
      namespace: 'tavern',
      method: 'deleteSave',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-tavern-fengyue-api/types#TavernLoadRequest',
            schema: _deepseek_ai_dsh_api_tavern_tavern_deleteSave_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-tavern-fengyue-api/types#TavernAckValue',
        schema: _deepseek_ai_dsh_api_tavern_tavern_deleteSave_result$schema,
      },
      sourceLocation: {"file":"packages/api/tavern/src/index.ts","line":318,"column":9},
    },
    {
      id: 'dsh-tavern-fengyue-api#tavern/deleteSession',
      service: 'tavernApi',
      namespace: 'tavern',
      method: 'deleteSession',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-tavern-fengyue-api/types#TavernSessionRequest',
            schema: _deepseek_ai_dsh_api_tavern_tavern_deleteSession_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-tavern-fengyue-api/types#TavernAckValue',
        schema: _deepseek_ai_dsh_api_tavern_tavern_deleteSession_result$schema,
      },
      sourceLocation: {"file":"packages/api/tavern/src/index.ts","line":448,"column":9},
    },
    {
      id: 'dsh-tavern-fengyue-api#tavern/draftCard',
      service: 'tavernApi',
      namespace: 'tavern',
      method: 'draftCard',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-tavern-fengyue-api/types#TavernSessionRequest',
            schema: _deepseek_ai_dsh_api_tavern_tavern_draftCard_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-tavern-fengyue-api/types#TavernAckValue',
        schema: _deepseek_ai_dsh_api_tavern_tavern_draftCard_result$schema,
      },
      sourceLocation: {"file":"packages/api/tavern/src/index.ts","line":244,"column":9},
    },
    {
      id: 'dsh-tavern-fengyue-api#tavern/editDirty',
      service: 'tavernApi',
      namespace: 'tavern',
      method: 'editDirty',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-tavern-fengyue-api/types#TavernEditDirtyRequest',
            schema: _deepseek_ai_dsh_api_tavern_tavern_editDirty_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-tavern-fengyue-api/types#TavernEditDirtyValue',
        schema: _deepseek_ai_dsh_api_tavern_tavern_editDirty_result$schema,
      },
      sourceLocation: {"file":"packages/api/tavern/src/index.ts","line":441,"column":9},
    },
    {
      id: 'dsh-tavern-fengyue-api#tavern/editFromLibrary',
      service: 'tavernApi',
      namespace: 'tavern',
      method: 'editFromLibrary',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-tavern-fengyue-api/types#TavernImportLibraryRequest',
            schema: _deepseek_ai_dsh_api_tavern_tavern_editFromLibrary_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-tavern-fengyue-api/types#TavernAckValue',
        schema: _deepseek_ai_dsh_api_tavern_tavern_editFromLibrary_result$schema,
      },
      sourceLocation: {"file":"packages/api/tavern/src/index.ts","line":254,"column":9},
    },
    {
      id: 'dsh-tavern-fengyue-api#tavern/ensureWriter',
      service: 'tavernApi',
      namespace: 'tavern',
      method: 'ensureWriter',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-tavern-fengyue-api/types#TavernEnsureWriterRequest',
            schema: _deepseek_ai_dsh_api_tavern_tavern_ensureWriter_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-tavern-fengyue-api/types#TavernEnsureWriterValue',
        schema: _deepseek_ai_dsh_api_tavern_tavern_ensureWriter_result$schema,
      },
      sourceLocation: {"file":"packages/api/tavern/src/index.ts","line":388,"column":9},
    },
    {
      id: 'dsh-tavern-fengyue-api#tavern/fileOp',
      service: 'tavernApi',
      namespace: 'tavern',
      method: 'fileOp',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-tavern-fengyue-api/types#TavernFileOpRequest',
            schema: _deepseek_ai_dsh_api_tavern_tavern_fileOp_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-tavern-fengyue-api/types#TavernAckValue',
        schema: _deepseek_ai_dsh_api_tavern_tavern_fileOp_result$schema,
      },
      sourceLocation: {"file":"packages/api/tavern/src/index.ts","line":361,"column":9},
    },
    {
      id: 'dsh-tavern-fengyue-api#tavern/importFromLibrary',
      service: 'tavernApi',
      namespace: 'tavern',
      method: 'importFromLibrary',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-tavern-fengyue-api/types#TavernImportLibraryRequest',
            schema: _deepseek_ai_dsh_api_tavern_tavern_importFromLibrary_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-tavern-fengyue-api/types#TavernAckValue',
        schema: _deepseek_ai_dsh_api_tavern_tavern_importFromLibrary_result$schema,
      },
      sourceLocation: {"file":"packages/api/tavern/src/index.ts","line":224,"column":9},
    },
    {
      id: 'dsh-tavern-fengyue-api#tavern/library',
      service: 'tavernApi',
      namespace: 'tavern',
      method: 'library',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: '_request',
          wire: '_request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-tavern-fengyue-api#tavern/library:_request',
            schema: _deepseek_ai_dsh_api_tavern_tavern_library_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-tavern-fengyue-api/types#TavernLibraryValue',
        schema: _deepseek_ai_dsh_api_tavern_tavern_library_result$schema,
      },
      sourceLocation: {"file":"packages/api/tavern/src/index.ts","line":210,"column":9},
    },
    {
      id: 'dsh-tavern-fengyue-api#tavern/load',
      service: 'tavernApi',
      namespace: 'tavern',
      method: 'load',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-tavern-fengyue-api/types#TavernLoadRequest',
            schema: _deepseek_ai_dsh_api_tavern_tavern_load_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-tavern-fengyue-api/types#TavernRebindValue',
        schema: _deepseek_ai_dsh_api_tavern_tavern_load_result$schema,
      },
      sourceLocation: {"file":"packages/api/tavern/src/index.ts","line":298,"column":9},
    },
    {
      id: 'dsh-tavern-fengyue-api#tavern/opening',
      service: 'tavernApi',
      namespace: 'tavern',
      method: 'opening',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-tavern-fengyue-api/types#TavernSessionRequest',
            schema: _deepseek_ai_dsh_api_tavern_tavern_opening_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-tavern-fengyue-api/types#TavernOpeningValue',
        schema: _deepseek_ai_dsh_api_tavern_tavern_opening_result$schema,
      },
      sourceLocation: {"file":"packages/api/tavern/src/index.ts","line":274,"column":9},
    },
    {
      id: 'dsh-tavern-fengyue-api#tavern/prompt',
      service: 'tavernApi',
      namespace: 'tavern',
      method: 'prompt',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-tavern-fengyue-api/types#TavernPromptRequest',
            schema: _deepseek_ai_dsh_api_tavern_tavern_prompt_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-tavern-fengyue-api/types#TavernPromptValue',
        schema: _deepseek_ai_dsh_api_tavern_tavern_prompt_result$schema,
      },
      sourceLocation: {"file":"packages/api/tavern/src/index.ts","line":458,"column":9},
    },
    {
      id: 'dsh-tavern-fengyue-api#tavern/publishCard',
      service: 'tavernApi',
      namespace: 'tavern',
      method: 'publishCard',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-tavern-fengyue-api/types#TavernPublishRequest',
            schema: _deepseek_ai_dsh_api_tavern_tavern_publishCard_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-tavern-fengyue-api/types#TavernPublishValue',
        schema: _deepseek_ai_dsh_api_tavern_tavern_publishCard_result$schema,
      },
      sourceLocation: {"file":"packages/api/tavern/src/index.ts","line":427,"column":9},
    },
    {
      id: 'dsh-tavern-fengyue-api#tavern/readAsset',
      service: 'tavernApi',
      namespace: 'tavern',
      method: 'readAsset',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-tavern-fengyue-api/types#TavernReadAssetRequest',
            schema: _deepseek_ai_dsh_api_tavern_tavern_readAsset_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-tavern-fengyue-api/types#TavernReadAssetValue',
        schema: _deepseek_ai_dsh_api_tavern_tavern_readAsset_result$schema,
      },
      sourceLocation: {"file":"packages/api/tavern/src/index.ts","line":371,"column":9},
    },
    {
      id: 'dsh-tavern-fengyue-api#tavern/readLibraryAsset',
      service: 'tavernApi',
      namespace: 'tavern',
      method: 'readLibraryAsset',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-tavern-fengyue-api/types#TavernReadLibraryAssetRequest',
            schema: _deepseek_ai_dsh_api_tavern_tavern_readLibraryAsset_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-tavern-fengyue-api/types#TavernReadLibraryAssetValue',
        schema: _deepseek_ai_dsh_api_tavern_tavern_readLibraryAsset_result$schema,
      },
      sourceLocation: {"file":"packages/api/tavern/src/index.ts","line":410,"column":9},
    },
    {
      id: 'dsh-tavern-fengyue-api#tavern/readText',
      service: 'tavernApi',
      namespace: 'tavern',
      method: 'readText',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-tavern-fengyue-api/types#TavernReadTextRequest',
            schema: _deepseek_ai_dsh_api_tavern_tavern_readText_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-tavern-fengyue-api/types#TavernReadTextValue',
        schema: _deepseek_ai_dsh_api_tavern_tavern_readText_result$schema,
      },
      sourceLocation: {"file":"packages/api/tavern/src/index.ts","line":344,"column":9},
    },
    {
      id: 'dsh-tavern-fengyue-api#tavern/reset',
      service: 'tavernApi',
      namespace: 'tavern',
      method: 'reset',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-tavern-fengyue-api/types#TavernSessionRequest',
            schema: _deepseek_ai_dsh_api_tavern_tavern_reset_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-tavern-fengyue-api/types#TavernRebindValue',
        schema: _deepseek_ai_dsh_api_tavern_tavern_reset_result$schema,
      },
      sourceLocation: {"file":"packages/api/tavern/src/index.ts","line":330,"column":9},
    },
    {
      id: 'dsh-tavern-fengyue-api#tavern/retryPoint',
      service: 'tavernApi',
      namespace: 'tavern',
      method: 'retryPoint',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-tavern-fengyue-api/types#TavernSessionRequest',
            schema: _deepseek_ai_dsh_api_tavern_tavern_retryPoint_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-tavern-fengyue-api/types#TavernRetryPointValue',
        schema: _deepseek_ai_dsh_api_tavern_tavern_retryPoint_result$schema,
      },
      sourceLocation: {"file":"packages/api/tavern/src/index.ts","line":308,"column":9},
    },
    {
      id: 'dsh-tavern-fengyue-api#tavern/runScript',
      service: 'tavernApi',
      namespace: 'tavern',
      method: 'runScript',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-tavern-fengyue-api/types#TavernRunScriptRequest',
            schema: _deepseek_ai_dsh_api_tavern_tavern_runScript_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-tavern-fengyue-api/types#TavernRunScriptValue',
        schema: _deepseek_ai_dsh_api_tavern_tavern_runScript_result$schema,
      },
      sourceLocation: {"file":"packages/api/tavern/src/index.ts","line":472,"column":9},
    },
    {
      id: 'dsh-tavern-fengyue-api#tavern/save',
      service: 'tavernApi',
      namespace: 'tavern',
      method: 'save',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-tavern-fengyue-api/types#TavernSaveRequest',
            schema: _deepseek_ai_dsh_api_tavern_tavern_save_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-tavern-fengyue-api/types#TavernAckValue',
        schema: _deepseek_ai_dsh_api_tavern_tavern_save_result$schema,
      },
      sourceLocation: {"file":"packages/api/tavern/src/index.ts","line":288,"column":9},
    },
    {
      id: 'dsh-tavern-fengyue-api#tavern/saveEdit',
      service: 'tavernApi',
      namespace: 'tavern',
      method: 'saveEdit',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-tavern-fengyue-api/types#TavernSaveEditRequest',
            schema: _deepseek_ai_dsh_api_tavern_tavern_saveEdit_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-tavern-fengyue-api/types#TavernPublishValue',
        schema: _deepseek_ai_dsh_api_tavern_tavern_saveEdit_result$schema,
      },
      sourceLocation: {"file":"packages/api/tavern/src/index.ts","line":434,"column":9},
    },
    {
      id: 'dsh-tavern-fengyue-api#tavern/saves',
      service: 'tavernApi',
      namespace: 'tavern',
      method: 'saves',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-tavern-fengyue-api/types#TavernSessionRequest',
            schema: _deepseek_ai_dsh_api_tavern_tavern_saves_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-tavern-fengyue-api/types#TavernSavesValue',
        schema: _deepseek_ai_dsh_api_tavern_tavern_saves_result$schema,
      },
      sourceLocation: {"file":"packages/api/tavern/src/index.ts","line":281,"column":9},
    },
    {
      id: 'dsh-tavern-fengyue-api#tavern/state',
      service: 'tavernApi',
      namespace: 'tavern',
      method: 'state',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-tavern-fengyue-api/types#TavernSessionRequest',
            schema: _deepseek_ai_dsh_api_tavern_tavern_state_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-tavern-fengyue-api/types#TavernStateValue',
        schema: _deepseek_ai_dsh_api_tavern_tavern_state_result$schema,
      },
      sourceLocation: {"file":"packages/api/tavern/src/index.ts","line":196,"column":9},
    },
    {
      id: 'dsh-tavern-fengyue-api#tavern/stop',
      service: 'tavernApi',
      namespace: 'tavern',
      method: 'stop',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-tavern-fengyue-api/types#TavernStopRequest',
            schema: _deepseek_ai_dsh_api_tavern_tavern_stop_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-tavern-fengyue-api/types#TavernStopValue',
        schema: _deepseek_ai_dsh_api_tavern_tavern_stop_result$schema,
      },
      sourceLocation: {"file":"packages/api/tavern/src/index.ts","line":478,"column":3},
    },
    {
      id: 'dsh-tavern-fengyue-api#tavern/tailTranscript',
      service: 'tavernApi',
      namespace: 'tavern',
      method: 'tailTranscript',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-tavern-fengyue-api/types#TavernSessionRequest',
            schema: _deepseek_ai_dsh_api_tavern_tavern_tailTranscript_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-tavern-fengyue-api/types#TavernTailTranscriptValue',
        schema: _deepseek_ai_dsh_api_tavern_tavern_tailTranscript_result$schema,
      },
      sourceLocation: {"file":"packages/api/tavern/src/index.ts","line":488,"column":9},
    },
    {
      id: 'dsh-tavern-fengyue-api#tavern/tree',
      service: 'tavernApi',
      namespace: 'tavern',
      method: 'tree',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-tavern-fengyue-api/types#TavernSessionRequest',
            schema: _deepseek_ai_dsh_api_tavern_tavern_tree_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-tavern-fengyue-api/types#TavernTreeValue',
        schema: _deepseek_ai_dsh_api_tavern_tavern_tree_result$schema,
      },
      sourceLocation: {"file":"packages/api/tavern/src/index.ts","line":337,"column":9},
    },
    {
      id: 'dsh-tavern-fengyue-api#tavern/workspaces',
      service: 'tavernApi',
      namespace: 'tavern',
      method: 'workspaces',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: '_request',
          wire: '_request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-tavern-fengyue-api#tavern/workspaces:_request',
            schema: _deepseek_ai_dsh_api_tavern_tavern_workspaces_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-tavern-fengyue-api/types#TavernWorkspacesValue',
        schema: _deepseek_ai_dsh_api_tavern_tavern_workspaces_result$schema,
      },
      sourceLocation: {"file":"packages/api/tavern/src/index.ts","line":182,"column":9},
    },
    {
      id: 'dsh-tavern-fengyue-api#tavern/writeAsset',
      service: 'tavernApi',
      namespace: 'tavern',
      method: 'writeAsset',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-tavern-fengyue-api/types#TavernWriteAssetRequest',
            schema: _deepseek_ai_dsh_api_tavern_tavern_writeAsset_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-tavern-fengyue-api/types#TavernAckValue',
        schema: _deepseek_ai_dsh_api_tavern_tavern_writeAsset_result$schema,
      },
      sourceLocation: {"file":"packages/api/tavern/src/index.ts","line":378,"column":9},
    },
    {
      id: 'dsh-tavern-fengyue-api#tavern/writeText',
      service: 'tavernApi',
      namespace: 'tavern',
      method: 'writeText',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-tavern-fengyue-api/types#TavernWriteTextRequest',
            schema: _deepseek_ai_dsh_api_tavern_tavern_writeText_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-tavern-fengyue-api/types#TavernAckValue',
        schema: _deepseek_ai_dsh_api_tavern_tavern_writeText_result$schema,
      },
      sourceLocation: {"file":"packages/api/tavern/src/index.ts","line":351,"column":9},
    },
  ],
  model: {
    "services": [
      {
        "description": "Host service backing `ctx.remote.tavern` over the tavern engine.",
        "summary": "Host service backing `ctx.remote.tavern` over the tavern engine.",
        "tags": [],
        "jsDoc": "/** Host service backing `ctx.remote.tavern` over the tavern engine. */",
        "key": "tavernApi",
        "exportName": "TavernApi",
        "members": [
          {
            "kind": "method",
            "name": "workspaces",
            "signature": "@Remote async workspaces(_request: Record<never, never>, signal: AbortSignal): Promise<TavernWorkspacesValue>",
            "jsDoc": "/** @param signal – cancels the call. */"
          },
          {
            "kind": "method",
            "name": "createSession",
            "signature": "@Remote async createSession(_request: TavernCreateSessionRequest, signal: AbortSignal): Promise<TavernCreateSessionValue>",
            "jsDoc": "/** @param signal – caller lifetime; the engine's session create retains its own semantics. */"
          },
          {
            "kind": "method",
            "name": "state",
            "signature": "@Remote async state(request: TavernSessionRequest, signal: AbortSignal): Promise<TavernStateValue>",
            "jsDoc": "/** @param request - session identity. @param signal – cancels the call. */"
          },
          {
            "kind": "method",
            "name": "library",
            "signature": "@Remote async library(_request: Record<never, never>, signal: AbortSignal): Promise<TavernLibraryValue>",
            "jsDoc": "/** @param signal – cancels the call. */"
          },
          {
            "kind": "method",
            "name": "importFromLibrary",
            "signature": "@Remote async importFromLibrary(request: TavernImportLibraryRequest, signal: AbortSignal): Promise<TavernAckValue>",
            "jsDoc": "/** @param request - the card and its receiving session. @param signal – cancels the call. */"
          },
          {
            "kind": "method",
            "name": "deleteCard",
            "signature": "@Remote async deleteCard(request: TavernDeleteCardRequest, signal: AbortSignal): Promise<TavernAckValue>",
            "jsDoc": "/** @param request - the card to delete. @param signal – cancels the call. */"
          },
          {
            "kind": "method",
            "name": "draftCard",
            "signature": "@Remote async draftCard(request: TavernSessionRequest, signal: AbortSignal): Promise<TavernAckValue>",
            "jsDoc": "/** @param request - session identity. @param signal – cancels the call. */"
          },
          {
            "kind": "method",
            "name": "editFromLibrary",
            "signature": "@Remote async editFromLibrary(request: TavernImportLibraryRequest, signal: AbortSignal): Promise<TavernAckValue>",
            "jsDoc": "/** @param request - the card and its receiving session. @param signal – cancels the call. */"
          },
          {
            "kind": "method",
            "name": "cancelEdit",
            "signature": "@Remote async cancelEdit(request: TavernSessionRequest, signal: AbortSignal): Promise<TavernAckValue>",
            "jsDoc": "/** @param request - session identity. @param signal – cancels the call. */"
          },
          {
            "kind": "method",
            "name": "opening",
            "signature": "@Remote async opening(request: TavernSessionRequest, signal: AbortSignal): Promise<TavernOpeningValue>",
            "jsDoc": "/** @param request - session identity. @param signal – cancels the call. */"
          },
          {
            "kind": "method",
            "name": "saves",
            "signature": "@Remote async saves(request: TavernSessionRequest, signal: AbortSignal): Promise<TavernSavesValue>",
            "jsDoc": "/** @param request - session identity. @param signal – cancels the call. */"
          },
          {
            "kind": "method",
            "name": "save",
            "signature": "@Remote async save(request: TavernSaveRequest, signal: AbortSignal): Promise<TavernAckValue>",
            "jsDoc": "/** @param request - session, save name, and composer draft. @param signal – cancels the call. */"
          },
          {
            "kind": "method",
            "name": "load",
            "signature": "@Remote async load(request: TavernLoadRequest, signal: AbortSignal): Promise<TavernRebindValue>",
            "jsDoc": "/** @param request - session and save name. @param signal – cancels the call. */"
          },
          {
            "kind": "method",
            "name": "retryPoint",
            "signature": "@Remote async retryPoint(request: TavernSessionRequest, signal: AbortSignal): Promise<TavernRetryPointValue>",
            "jsDoc": "/** @param request - session identity. @param signal - cancels the rebind. */"
          },
          {
            "kind": "method",
            "name": "deleteSave",
            "signature": "@Remote async deleteSave(request: TavernLoadRequest, signal: AbortSignal): Promise<TavernAckValue>",
            "jsDoc": "/** @param request - session and save name. @param signal – cancels the call. */"
          },
          {
            "kind": "method",
            "name": "reset",
            "signature": "@Remote async reset(request: TavernSessionRequest, signal: AbortSignal): Promise<TavernRebindValue>",
            "jsDoc": "/** @param request - session identity. @param signal – cancels the call.\n * @returns the fresh session id the workspace rebinds to; a cleared workspace\n *   restores no composer draft. */"
          },
          {
            "kind": "method",
            "name": "tree",
            "signature": "@Remote async tree(request: TavernSessionRequest, signal: AbortSignal): Promise<TavernTreeValue>",
            "jsDoc": "/** @param request - session identity. @param signal – cancels the call. */"
          },
          {
            "kind": "method",
            "name": "readText",
            "signature": "@Remote async readText(request: TavernReadTextRequest, signal: AbortSignal): Promise<TavernReadTextValue>",
            "jsDoc": "/** @param request - session and path. @param signal – cancels the call. */"
          },
          {
            "kind": "method",
            "name": "writeText",
            "signature": "@Remote async writeText(request: TavernWriteTextRequest, signal: AbortSignal): Promise<TavernAckValue>",
            "jsDoc": "/** @param request - session, path, and text. @param signal – cancels the call. */"
          },
          {
            "kind": "method",
            "name": "fileOp",
            "signature": "@Remote async fileOp(request: TavernFileOpRequest, signal: AbortSignal): Promise<TavernAckValue>",
            "jsDoc": "/** @param request - session and operation. @param signal – cancels the call. */"
          },
          {
            "kind": "method",
            "name": "readAsset",
            "signature": "@Remote async readAsset(request: TavernReadAssetRequest, signal: AbortSignal): Promise<TavernReadAssetValue>",
            "jsDoc": "/** @param request - session and path. @param signal - cancels the call. */"
          },
          {
            "kind": "method",
            "name": "writeAsset",
            "signature": "@Remote async writeAsset(request: TavernWriteAssetRequest, signal: AbortSignal): Promise<TavernAckValue>",
            "jsDoc": "/** @param request - session, path, and base64 content. @param signal - cancels the call. */"
          },
          {
            "kind": "method",
            "name": "ensureWriter",
            "signature": "@Remote async ensureWriter(request: TavernEnsureWriterRequest, signal: AbortSignal): Promise<TavernEnsureWriterValue>",
            "jsDoc": "/** @param request - the workspace-owning session. @param signal - cancels the call. */"
          },
          {
            "kind": "method",
            "name": "commitImport",
            "signature": "@Remote async commitImport(request: TavernCommitImportRequest, signal: AbortSignal): Promise<TavernCommitImportValue>",
            "jsDoc": "/** @param request - session, title, and files. @param signal - cancels the call. */"
          },
          {
            "kind": "method",
            "name": "readLibraryAsset",
            "signature": "@Remote async readLibraryAsset(request: TavernReadLibraryAssetRequest, signal: AbortSignal): Promise<TavernReadLibraryAssetValue>",
            "jsDoc": "/** @param request - card name and asset path. @param signal - cancels the call. */"
          },
          {
            "kind": "method",
            "name": "cancelDraft",
            "signature": "@Remote async cancelDraft(request: TavernCancelDraftRequest, signal: AbortSignal): Promise<TavernAckValue>",
            "jsDoc": "/** @param request - session identity. @param signal - cancels the call. */"
          },
          {
            "kind": "method",
            "name": "publishCard",
            "signature": "@Remote async publishCard(request: TavernPublishRequest, signal: AbortSignal): Promise<TavernPublishValue>",
            "jsDoc": "/** @param request - session identity. @param signal - cancels the call. */"
          },
          {
            "kind": "method",
            "name": "saveEdit",
            "signature": "@Remote async saveEdit(request: TavernSaveEditRequest, signal: AbortSignal): Promise<TavernPublishValue>",
            "jsDoc": "/** @param request - session identity. @param signal - cancels the call. */"
          },
          {
            "kind": "method",
            "name": "editDirty",
            "signature": "@Remote async editDirty(request: TavernEditDirtyRequest, signal: AbortSignal): Promise<TavernEditDirtyValue>",
            "jsDoc": "/** @param request - session identity. @param signal - cancels the call. */"
          },
          {
            "kind": "method",
            "name": "deleteSession",
            "signature": "@Remote async deleteSession(request: TavernSessionRequest, signal: AbortSignal): Promise<TavernAckValue>",
            "jsDoc": "/** @param request - session identity. @param signal - cancels the call. */"
          },
          {
            "kind": "method",
            "name": "prompt",
            "signature": "@Remote async prompt(request: TavernPromptRequest, signal: AbortSignal): Promise<TavernPromptValue>",
            "jsDoc": "/** @param request - session, raw text, client-minted identity, and optional zone. @param signal – cancels the call. */"
          },
          {
            "kind": "method",
            "name": "runScript",
            "signature": "@Remote async runScript(request: TavernRunScriptRequest, signal: AbortSignal): Promise<TavernRunScriptValue>",
            "jsDoc": "/**\n * @param request - session identity, the script base name, and positional argv.\n * @param signal - cancels the running script (the spawn contract matches the prompt face).\n */"
          },
          {
            "kind": "method",
            "name": "stop",
            "signature": "@Remote stop(request: TavernStopRequest, signal: AbortSignal): TavernStopValue"
          },
          {
            "kind": "method",
            "name": "tailTranscript",
            "signature": "@Remote async tailTranscript(request: TavernSessionRequest, signal: AbortSignal): Promise<TavernTailTranscriptValue>",
            "jsDoc": "/**\n * @param request - the session whose tail catalog to project.\n * @param signal - unused; the method awaits only local reads.\n */"
          }
        ],
        "types": [
          {
            "name": "Branded",
            "declaration": "export type Branded<B extends string> = string & { readonly [BRAND]: B; };"
          },
          {
            "name": "SessionId",
            "declaration": "export type SessionId = Branded<'SessionId'>;"
          },
          {
            "name": "TavernAckValue",
            "declaration": "export interface TavernAckValue {\n    readonly ok: true;\n}"
          },
          {
            "name": "TavernCancelDraftRequest",
            "declaration": "export interface TavernCancelDraftRequest extends TavernSessionRequest {\n}"
          },
          {
            "name": "TavernCommitImportRequest",
            "declaration": "export interface TavernCommitImportRequest {\n    readonly sessionId: SessionId;\n    readonly title: string;\n    readonly files: readonly { readonly path: string; readonly content: string; }[];\n}"
          },
          {
            "name": "TavernCommitImportValue",
            "declaration": "export interface TavernCommitImportValue {\n    readonly name: string;\n}"
          },
          {
            "name": "TavernCreateSessionRequest",
            "declaration": "export interface TavernCreateSessionRequest {\n    readonly nop?: undefined;\n}"
          },
          {
            "name": "TavernCreateSessionValue",
            "declaration": "export interface TavernCreateSessionValue {\n    readonly sessionId: SessionId;\n}"
          },
          {
            "name": "TavernDeleteCardRequest",
            "declaration": "export interface TavernDeleteCardRequest {\n    readonly name: string;\n}"
          },
          {
            "name": "TavernEditDirtyRequest",
            "declaration": "export interface TavernEditDirtyRequest extends TavernSessionRequest {\n}"
          },
          {
            "name": "TavernEditDirtyValue",
            "declaration": "export interface TavernEditDirtyValue {\n    readonly dirty: boolean;\n}"
          },
          {
            "name": "TavernEnsureWriterRequest",
            "declaration": "export interface TavernEnsureWriterRequest extends TavernSessionRequest {\n}"
          },
          {
            "name": "TavernEnsureWriterValue",
            "declaration": "export interface TavernEnsureWriterValue {\n    readonly sessionId: SessionId;\n}"
          },
          {
            "name": "TavernFileOp",
            "declaration": "export type TavernFileOp = { readonly kind: 'create'; readonly path: string; } | { readonly kind: 'mkdir'; readonly path: string; } | { readonly kind: 'move'; readonly from: string; readonly to: string; } | { readonly kind: 'delete'; readonly path: string; };"
          },
          {
            "name": "TavernFileOpRequest",
            "declaration": "export interface TavernFileOpRequest {\n    readonly sessionId: SessionId;\n    readonly op: TavernFileOp;\n}"
          },
          {
            "name": "TavernImportLibraryRequest",
            "declaration": "export interface TavernImportLibraryRequest {\n    readonly sessionId: SessionId;\n    readonly name: string;\n}"
          },
          {
            "name": "TavernLibraryCardWire",
            "declaration": "export interface TavernLibraryCardWire {\n    readonly name: string;\n    readonly title: string;\n    readonly desc: string;\n    readonly cover: string;\n}"
          },
          {
            "name": "TavernLibraryValue",
            "declaration": "export interface TavernLibraryValue {\n    readonly cards: readonly TavernLibraryCardWire[];\n}"
          },
          {
            "name": "TavernLoadRequest",
            "declaration": "export interface TavernLoadRequest {\n    readonly sessionId: SessionId;\n    readonly name: string;\n}"
          },
          {
            "name": "TavernOpeningValue",
            "declaration": "export interface TavernOpeningValue {\n    readonly html: string | null;\n}"
          },
          {
            "name": "TavernPromptRequest",
            "declaration": "export interface TavernPromptRequest {\n    readonly sessionId: SessionId;\n    readonly text: string;\n    readonly requestId: string;\n    readonly clientTimeZone?: string;\n}"
          },
          {
            "name": "TavernPromptValue",
            "declaration": "export interface TavernPromptValue {\n    readonly accepted: boolean;\n    readonly scriptFailures?: TavernScriptFailure[];\n}"
          },
          {
            "name": "TavernPublishRequest",
            "declaration": "export interface TavernPublishRequest extends TavernSessionRequest {\n}"
          },
          {
            "name": "TavernPublishValue",
            "declaration": "export interface TavernPublishValue {\n    readonly name: string;\n}"
          },
          {
            "name": "TavernReadAssetRequest",
            "declaration": "export interface TavernReadAssetRequest {\n    readonly sessionId: SessionId;\n    readonly path: string;\n}"
          },
          {
            "name": "TavernReadAssetValue",
            "declaration": "export interface TavernReadAssetValue {\n    readonly dataUrl: string;\n}"
          },
          {
            "name": "TavernReadLibraryAssetRequest",
            "declaration": "export interface TavernReadLibraryAssetRequest {\n    readonly name: string;\n    readonly path: string;\n}"
          },
          {
            "name": "TavernReadLibraryAssetValue",
            "declaration": "export interface TavernReadLibraryAssetValue {\n    readonly dataUrl: string;\n}"
          },
          {
            "name": "TavernReadTextRequest",
            "declaration": "export interface TavernReadTextRequest {\n    readonly sessionId: SessionId;\n    readonly path: string;\n}"
          },
          {
            "name": "TavernReadTextValue",
            "declaration": "export interface TavernReadTextValue {\n    readonly text: string;\n}"
          },
          {
            "name": "TavernRebindValue",
            "declaration": "export interface TavernRebindValue {\n    readonly sessionId: SessionId;\n    readonly draft: string;\n}"
          },
          {
            "name": "TavernRetryPointValue",
            "declaration": "export interface TavernRetryPointValue {\n    readonly sessionId: SessionId;\n    readonly text: string;\n}"
          },
          {
            "name": "TavernRunScriptRequest",
            "declaration": "export interface TavernRunScriptRequest extends TavernSessionRequest {\n    readonly name: string;\n    readonly args: readonly string[];\n}"
          },
          {
            "name": "TavernRunScriptValue",
            "declaration": "export interface TavernRunScriptValue {\n    readonly text: string;\n}"
          },
          {
            "name": "TavernSaveEditRequest",
            "declaration": "export interface TavernSaveEditRequest extends TavernSessionRequest {\n}"
          },
          {
            "name": "TavernSaveRequest",
            "declaration": "export interface TavernSaveRequest {\n    readonly sessionId: SessionId;\n    readonly name: string;\n    readonly draft: string;\n}"
          },
          {
            "name": "TavernSavesValue",
            "declaration": "export interface TavernSavesValue {\n    readonly saves: readonly TavernSaveWire[];\n}"
          },
          {
            "name": "TavernSaveWire",
            "declaration": "export interface TavernSaveWire {\n    readonly name: string;\n    readonly type: 'auto' | 'manual';\n    readonly summary: string;\n}"
          },
          {
            "name": "TavernScriptFailure",
            "declaration": "export interface TavernScriptFailure {\n    readonly name: string;\n    readonly reason: 'parse' | 'depth' | 'args' | 'limit' | 'missing' | 'exit' | 'timeout' | 'abort';\n    readonly exitCode?: number;\n}"
          },
          {
            "name": "TavernSessionRequest",
            "declaration": "export interface TavernSessionRequest {\n    readonly sessionId: SessionId;\n}"
          },
          {
            "name": "TavernSessionRowWire",
            "declaration": "export interface TavernSessionRowWire {\n    readonly name: string;\n    readonly sessionId: string | null;\n    readonly hasCard: boolean;\n    readonly title: string;\n    readonly desc: string;\n}"
          },
          {
            "name": "TavernStateValue",
            "declaration": "export interface TavernStateValue {\n    readonly hasCard: boolean;\n    readonly maintenanceOn: boolean;\n    readonly title: string;\n    readonly desc: string;\n    readonly cover: string;\n    readonly drafting: boolean;\n    readonly editing: string | null;\n    readonly tailRunning: boolean;\n    readonly retryable: boolean;\n}"
          },
          {
            "name": "TavernStopRequest",
            "declaration": "export interface TavernStopRequest {\n    readonly sessionId: SessionId;\n}"
          },
          {
            "name": "TavernStopValue",
            "declaration": "export interface TavernStopValue {\n    readonly accepted: true;\n    readonly tailStopped: boolean;\n}"
          },
          {
            "name": "TavernTailActionWire",
            "declaration": "export interface TavernTailActionWire {\n    readonly tool: string;\n    readonly detail: string;\n}"
          },
          {
            "name": "TavernTailRunWire",
            "declaration": "export interface TavernTailRunWire {\n    readonly childId: string;\n    readonly at: number;\n    readonly status: 'completed' | 'stopped' | 'error' | 'archived';\n    readonly actions: readonly TavernTailActionWire[];\n    readonly reply: string;\n}"
          },
          {
            "name": "TavernTailTranscriptValue",
            "declaration": "export interface TavernTailTranscriptValue {\n    readonly tails: readonly TavernTailRunWire[];\n}"
          },
          {
            "name": "TavernTreeValue",
            "declaration": "export interface TavernTreeValue {\n    readonly entries: readonly { readonly path: string; readonly dir: boolean; }[];\n}"
          },
          {
            "name": "TavernWorkspacesValue",
            "declaration": "export interface TavernWorkspacesValue {\n    readonly rows: readonly TavernSessionRowWire[];\n}"
          },
          {
            "name": "TavernWriteAssetRequest",
            "declaration": "export interface TavernWriteAssetRequest {\n    readonly sessionId: SessionId;\n    readonly path: string;\n    readonly dataBase64: string;\n}"
          },
          {
            "name": "TavernWriteTextRequest",
            "declaration": "export interface TavernWriteTextRequest {\n    readonly sessionId: SessionId;\n    readonly path: string;\n    readonly text: string;\n}"
          }
        ]
      }
    ],
    "events": [],
    "objects": []
  },
}
